services:
  monitoringlab:
    build: .
    container_name: monitoringlab-app
    ports:
      - "5080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      SelfBaseUrl: http://localhost:8080

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoringlab-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - monitoringlab

  grafana:
    image: grafana/grafana-oss:latest
    container_name: monitoringlab-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus